# Generated by Django 5.0.4 on 2024-05-13 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfol', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('deactive', 'Deactive')], max_length=20),
        ),
        migrations.AlterField(
            model_name='site',
            name='body',
            field=models.TextField(verbose_name='opisaniyasi'),
        ),
        migrations.AlterField(
            model_name='site',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('deactive', 'Deactive')], max_length=20),
        ),
        migrations.AlterField(
            model_name='site',
            name='subtitle',
            field=models.CharField(max_length=250, verbose_name='Kichik info'),
        ),
        migrations.AlterField(
            model_name='site',
            name='title',
            field=models.CharField(max_length=120, verbose_name='info'),
        ),
    ]
